import React, { FormEvent, useEffect, useMemo, useState } from "react";
import { NavLink, useLocation } from "react-router-dom";
import { DashboardData, fetchChatMessages, OperationalChatMessage, sendChatMessage } from "../api";
import { OctoMark } from "../components/OctoMark";
import { Icon } from "../components/Icon";
import { NervousSystem } from "../components/NervousSystem";
import { taskStatusLabels, statusProgress, formatRelative } from "../helpers";

const routes = [
  { to: "/", label: "Visão geral", icon: "grid", end: true },
  { to: "/chat", label: "Chat", icon: "chat", end: true },
  { to: "/backlog", label: "Fluxo de tasks", icon: "pulse" },
  { to: "/reviews", label: "Aguardando revisão", icon: "hand" },
  { to: "/projects", label: "Projetos", icon: "folder" },
  { to: "/providers", label: "Providers", icon: "spark" },
  { to: "/analytics", label: "Analytics & Custo", icon: "timeline" },
  { to: "/settings", label: "Configurações", icon: "settings" }
];

function PageTop({ title, eyebrow, action }: { title: string; eyebrow: string; action?: React.ReactNode }) {
  return <div className="top"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1></div>{action}</div>;
}

function AppSidebar({ pending }: { pending: number }) {
  return <aside>
    <NavLink className="brand" to="/" aria-label="Octomynd Maestro"><OctoMark /><div className="txt"><b>octomynd</b><span>Maestro</span></div></NavLink>
    <nav>
      {routes.map((item, index) => <React.Fragment key={item.to}>
        {index === 2 && <div className="nav-div" />}
        <NavLink to={item.to} end={item.end} className="nav-i"><Icon name={item.icon} />{item.label}{item.to === "/reviews" && pending > 0 ? <span className="badge-n">{pending}</span> : null}</NavLink>
      </React.Fragment>)}
    </nav>
    <div className="localfirst"><div className="pin" /><div><b>Local-first</b><span>127.0.0.1 · acesso privado</span></div></div>
  </aside>;
}

function V2Header({ onRefresh, onCreate, refreshing }: { onRefresh: () => void; onCreate: () => void; refreshing: boolean }) {
  return <div className="top"><div><div className="eyebrow">Central de Operação</div><h1>Bom dia, Everson.</h1></div><div className="top-actions"><div className="sync"><span className="d" /> sincronizado agora</div><button className="icon-btn" onClick={onRefresh} aria-label="Atualizar">{refreshing ? "…" : "↻"}</button><button className="btn-new" onClick={onCreate}>+ Nova task</button></div></div>;
}

function Overview({ data, onCreate }: { data: DashboardData; onCreate: () => void }) {
  const active = data.tasks.filter(t => !["done", "failed", "rejected", "cancelled"].includes(t.status));
  const recent = data.features.slice(0, 4);
  const costs = ["Gemini Antigravity", "Claude", "Codex", "Ollama (local)"];
  return <div className="view active">
    <V2Header onRefresh={() => window.location.reload()} onCreate={onCreate} refreshing={false} />
    <div className="hero"><div className="hero-left"><div className="live-tag"><span className="d" /> Sistema vivo</div><h2>Um cérebro.<br /><span>Braços que decidem.</span></h2><p>Dois terços dos neurônios de um polvo vivem nos braços. Cada agente aqui prova o próprio trabalho — e você mantém a decisão final.</p><div className="hero-chips"><span><b>{active.length}</b> tasks ativas</span><span><b>{data.summary.projects}</b> projetos locais</span><span>acesso <b>{data.daemon.access === "restricted" ? "restrito" : "aberto"}</b></span><span>autopilot <b>{data.autopilot.state}</b></span></div></div><div className="nerve"><NervousSystem agents={data.agents} /></div></div>
    <div className="metrics"><Metric label="Providers" value={data.agents.length} icon="✧" /><Metric label="Em movimento" value={data.summary.activeTasks} icon="⌁" /><Metric label="Na fila" value={data.summary.queuedTasks} icon="=" /><Metric label="Sua decisão" value={data.summary.humanGates} icon="♧" /></div>
    <div className="cols"><section className="panel"><PanelHead eyebrow="Runtime de features" title="Fluxo recente" meta={`${data.features.length} registradas`} />{recent.map(f => <FeatureLine key={f.id} feature={f} />)}</section><section className="panel"><PanelHead eyebrow="Distribuição de custo" title="Hoje" meta="USD" />{costs.map((name, i) => <div className="costrow" key={name}><span className="dot" style={{ background: ["#6f8f6a", "#c4622d", "#8a7c68", "#5c6f8f"][i] }} /><div className="lbl">{name}<small>0 tokens</small></div><div className="track"><i style={{ width: `${44 - i * 9}%` }} /></div><span className="amt">$0.00</span></div>)}<div className="divider" /><PanelHead eyebrow="Telemetria" title="Pulso do sistema" meta="ao vivo" /><div className="pulse-item"><span className="pd ok" /><div className="pt"><b>feature plan · worker inicializado</b><span>lifecycle cursor advanced</span></div><span className="tm">agora</span></div><div className="pulse-item"><span className="pd" /><div className="pt"><b>{active.length ? `task #${active[0].id} · em execução` : "fila livre"}</b><span>autopilot status</span></div><span className="tm">agora</span></div></section></div>
  </div>;
}

function Metric({ label, value, icon }: { label: string; value: number; icon: string }) { return <div className="metric"><div className="ico">{icon}</div><div className="k">{label}</div><div className="v">{value}</div></div>; }
function PanelHead({ eyebrow, title, meta }: { eyebrow: string; title: string; meta: string }) { return <div className="panel-head"><div><div className="lbl">{eyebrow}</div><h3>{title}</h3></div><div className="count">{meta}</div></div>; }
function FeatureLine({ feature }: { feature: DashboardData["features"][number] }) { const status = feature.status === "completed" ? "ok" : feature.status === "failed" ? "err" : "run"; const label = feature.status === "completed" ? "concluída" : feature.status === "failed" ? "falhou" : "rodando"; return <div className="task"><span className="id">#{String(feature.id).padStart(2, "0")}</span><span className={`st ${status}`}>{label}</span><div className="body"><b>{feature.name}</b><span>{feature.branchName}</span></div><div className="fiber"><svg viewBox="0 0 80 14"><path d="M2 7h76" stroke="#372c20" strokeWidth="2" /><path d={`M2 7h${feature.status === "completed" ? 76 : feature.status === "failed" ? 50 : 38}`} stroke={feature.status === "failed" ? "#b1503c" : feature.status === "completed" ? "#6f8f6a" : "#c4622d"} strokeWidth="2" /><circle cx={feature.status === "completed" ? 78 : feature.status === "failed" ? 52 : 40} cy="7" r="3" fill="#e8967a" /></svg></div><span className="arr">→</span></div>; }
function TaskLine({ task }: { task: DashboardData["tasks"][number] }) { return <div className="task"><span className="id">#{String(task.id).padStart(2, "0")}</span><span className={`st ${task.status === "failed" ? "err" : task.status === "done" ? "ok" : "run"}`}>{taskStatusLabels[task.status]}</span><div className="body"><b>{task.text}</b><span>{task.branchName ?? `criada ${formatRelative(task.createdAt)}`}</span></div><div className="fiber"><svg viewBox="0 0 80 14"><path d="M2 7h76" stroke="#372c20" strokeWidth="2" /><path d={`M2 7h${Math.max(8, statusProgress(task.status) * .76)}`} stroke={task.status === "failed" ? "#b1503c" : task.status === "done" ? "#6f8f6a" : "#c4622d"} strokeWidth="2" /><circle cx={Math.max(8, statusProgress(task.status) * .76)} cy="7" r="3" fill="#e8967a" /></svg></div><span className="arr">→</span></div>; }

function Chat({ data }: { data: DashboardData }) {
  const projectKey = data.projects[0]?.key ?? "maestro";
  const [messages, setMessages] = useState<OperationalChatMessage[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  useEffect(() => { void fetchChatMessages(projectKey).then(setMessages).catch(() => undefined); }, [projectKey]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!input.trim() || loading) return; const text = input.trim(); setInput(""); setLoading(true); try { const response = await sendChatMessage(projectKey, text); setMessages(await fetchChatMessages(projectKey)); if (!response) return; } finally { setLoading(false); } }
  return <div className="view active"><PageTop eyebrow="Orquestrador unificado" title="Chat" action={<select className="sel"><option>@{projectKey}</option></select>} /><div className="chat-wrap"><div className="chat-threads"><div className="thread-lbl">Conversas</div><div className="thread active"><b>Conversa do projeto</b><span>agora</span></div><div className="thread"><b>Status do sistema</b><span>recente</span></div><div className="thread"><b>Revisão de custo</b><span>recente</span></div></div><div className="chat-main"><div className="chat-head"><b>Conversa do projeto</b><span>@{projectKey}</span></div><div className="chat-body">{messages.length === 0 ? <div className="empty"><div className="ico">◯</div><h4>Comece uma conversa</h4><p>Pergunte sobre tasks, providers, custo ou peça uma ação governada.</p></div> : messages.map(message => <div className={`msg ${message.senderRole === "user" ? "user" : ""}`} key={message.id}><div className="msg-av">{message.senderRole === "user" ? "U" : "🐙"}</div><div><span className="msg-provider">{message.senderRole === "user" ? "você" : "Maestro"}</span><div className="msg-bub">{message.messageText}</div></div></div>)}</div><div className="chip-row"><span className="sugg" onClick={() => setInput("Quais tasks estão bloqueadas?")}>Quais tasks estão bloqueadas?</span><span className="sugg" onClick={() => setInput("Resumo de custo de hoje")}>Resumo de custo de hoje</span><span className="sugg" onClick={() => setInput("Listar providers ativos")}>Listar providers ativos</span></div><form className="chat-input" onSubmit={submit}><input value={input} onChange={e => setInput(e.target.value)} placeholder="Pergunte ao Maestro..." /><button className="chat-send" disabled={loading}>➤</button></form></div></div></div>;
}

function Flow({ data, onCreate }: { data: DashboardData; onCreate: () => void }) { const queued = data.tasks.filter(t => t.status === "queued").slice(0, 12); const active = data.tasks.filter(t => !["queued", "done", "failed", "rejected", "cancelled"].includes(t.status)); return <div className="view active"><PageTop eyebrow="Priorização" title="Fluxo de tasks" action={<div className="top-actions"><select className="sel"><option>Todos os projetos</option></select><button className="btn-new" onClick={onCreate}>+ Nova task</button></div>} /><section className="panel"><PanelHead eyebrow="Em andamento" title="Tasks em execução" meta={`${active.length} ativas`} />{active.length ? active.map(t => <TaskLine key={t.id} task={t} />) : <div className="empty"><div className="ico">ϟ</div><h4>Nenhuma task em execução</h4><p>As tasks na fila iniciarão automaticamente conforme os providers ficarem disponíveis.</p></div>}</section><section className="panel"><PanelHead eyebrow="Fila" title="Tasks na fila (Queued)" meta={`${queued.length} aguardando`} />{queued.length ? queued.map(t => <TaskLine key={t.id} task={t} />) : <div className="empty"><div className="ico">=</div><h4>Fila vazia</h4><p>Adicione novas demandas para colocar os agentes para trabalhar.</p></div>}</section><section className="panel"><PanelHead eyebrow="Planejamento" title="Feature Plans" meta={`${data.featurePlans.length} registrados`} /><div className="empty"><div className="ico">▤</div><h4>Feature Plans</h4><p>Planos agrupando várias tasks em um único PR consolidado aparecem aqui.</p></div></section></div>; }

function Reviews({ data }: { data: DashboardData }) { const pending = data.features.filter(f => ["reviewing", "waiting_checks", "changes_requested"].includes(f.status)); return <div className="view active"><PageTop eyebrow="Governança humana (Human Gate)" title="Aguardando revisão" action={<div className="chip"><b>{pending.length}</b> PRs pendentes</div>} /><p className="desc">Revise evidências, verificações de segurança e aprove ou solicite alterações antes do merge final.</p>{pending.length ? pending.map(f => <div className="pr-card" key={f.id}><div><span className="pr-tag">Human gate</span><h4>{f.name}</h4><p>{f.branchName} · checks e evidências disponíveis</p><div className="pr-actions"><a className="pr-btn" href={f.pullRequestUrl} target="_blank" rel="noreferrer">Ver diff</a><button className="pr-btn reject">Solicitar alterações</button></div></div><div><div className="seal">✓</div><div className="seal-lbl">Aprovar</div></div></div>) : <section className="panel"><div className="empty"><div className="ico">✓</div><h4>Nenhum PR aguardando revisão</h4><p>Quando um agente entregar trabalho, ele aparecerá aqui.</p></div></section>}</div>; }

function Projects({ data }: { data: DashboardData }) { return <div className="view active"><PageTop eyebrow="Workspace" title="Projetos" action={<button className="btn-ghost">+ Registrar projeto</button>} /><div className="panel-head"><div><div className="lbl">Diagnóstico</div><h3>Saúde dos projetos registrados</h3></div><div className="count">{data.projects.length} repositórios</div></div><div className="proj-grid">{data.projects.map(p => <div className="proj-status" key={p.key}><span className="tag ok">pronto</span><b>@{p.key}</b><p>Execution environment ready.</p></div>)}</div><div className="panel-head" style={{ marginTop: 30 }}><div><div className="lbl">Workspace</div><h3>Projetos locais</h3></div><div className="count">{data.projects.length} registrados</div></div><div className="proj-grid">{data.projects.map(p => <div className="proj-card" key={p.key}><div className="head"><div className="ic">{p.key[0]?.toUpperCase()}</div><div><span>@{p.key}</span><b>{p.name}</b></div></div><div className="proj-stats"><div><b>{data.tasks.filter(t => t.projectKey === p.key && !["done", "failed", "cancelled"].includes(t.status)).length}</b><span>ativas</span></div><div><b>{data.tasks.filter(t => t.projectKey === p.key).length}</b><span>total</span></div><div><b>main</b><span>branch</span></div></div><div className="proj-note">Nenhum agente trabalhando agora</div><div className="proj-foot">Repositório local protegido</div></div>)}</div></div>; }

function Providers({ data }: { data: DashboardData }) { return <div className="view active"><PageTop eyebrow="AI Routing" title="Providers" /><p className="desc">Conecte providers de nuvem, locais ou endpoints customizados e defina a prioridade por função.</p><div className="prov-grid"><div><div className="prov-group-lbl">Conectados</div>{data.agents.map(agent => <div className="prov-card" key={agent.id}><div className="head"><div className="av">{agent.label[0]}</div><div><b>{agent.label}</b><span>● {agentState(agent.state)}</span></div><span className="type-tag">provider</span></div><div className="prov-uso"><label>{agent.state === "ready" ? "ativo" : agent.state}</label></div></div>)}<div className="add-provider"><div className="plus">+</div><b>Conectar provider</b><span>Local, OpenAI-compatible, ou endpoint próprio</span></div></div><section className="panel"><PanelHead eyebrow="Control plane" title="Prioridade por função" meta="" />{["Planejamento", "Implementação", "Testes", "Review final", "Conversa"].map((name, i) => <div className="routing-row" key={name}><div className="rname">{name}</div><div><div className="field-lbl">Primeiro</div><select className="sel"><option>{data.agents[i % Math.max(data.agents.length, 1)]?.label ?? "Nenhum"}</option></select></div><div><div className="field-lbl">Regra</div><select className="sel"><option>Fallback automático</option></select></div></div>)}</section></div></div>; }
function agentState(state: string) { return state === "working" ? "trabalhando" : state === "ready" ? "pronto" : state; }

function Analytics({ data }: { data: DashboardData }) { return <div className="view active"><PageTop eyebrow="Métricas operacionais" title="Analytics & Custo" /><div className="metrics" style={{ gridTemplateColumns: "repeat(3,1fr)" }}><Metric label="Custo hoje / tokens" value={0} icon="$" /><Metric label="Taxa de conclusão" value={data.summary.completedTasks} icon="⌁" /><Metric label="Work graphs executados" value={data.workGraphs?.length ?? 0} icon="⌘" /></div><div className="cols"><section className="chartbox"><PanelHead eyebrow="Consumo de tokens" title="Token Usage" meta="input vs output" /><div className="bar-chart">{[40,65,30,80,55,90,45,70,35,60,50,75].map((h, i) => <i key={i} style={{ height: `${h}%` }} />)}</div></section><section className="chartbox"><PanelHead eyebrow="Distribuição de custos" title="Por provider" meta="USD" />{data.agents.map(a => <div className="costrow" key={a.id}><span className="dot" /><div className="lbl">{a.label}</div><div className="track"><i style={{ width: "30%" }} /></div><span className="amt">$0.00</span></div>)}</section></div></div>; }
function Settings({ data }: { data: DashboardData }) { return <div className="view active"><PageTop eyebrow="Configurações" title="Sistema" /><div className="cfg-block"><PanelHead eyebrow="Integração Telegram" title="Conexão do Telegram Bot" meta="bot ativo" /><div className="cfg-status"><span className="d" /> Telegram Bot conectado</div><div className="field"><label>HTTP API Bot Token (@BotFather)</label><input placeholder="Token configurado com segurança" type="password" /></div><button className="btn-new">Atualizar token do bot</button></div><div className="cfg-block"><PanelHead eyebrow="Autonomia" title="Configuração do Autopilot" meta={`estado: ${data.autopilot.state}`} /><div className="toggle-panel"><div className="tp"><div className="k">Autopilot status</div><div className="v"><span className="d" />{data.autopilot.enabled ? "Ativo (habilitado)" : "Desligado"}</div><p>O Maestro seleciona e avança automaticamente tasks elegíveis.</p></div><div className="tp"><div className="k">Modo de acesso do daemon</div><div className="v"><span className="d" />{data.daemon.access}</div><p>As worktrees isolam a execução e protegem o repositório.</p></div></div></div></div>; }

export function MaestroV2({ data, onRefresh, onCreate, refreshing }: { data: DashboardData; onRefresh: () => void; onCreate: () => void; refreshing: boolean }) {
  const location = useLocation();
  const pending = data.features.filter(f => ["reviewing", "waiting_checks", "changes_requested"].includes(f.status)).length;
  const page = location.pathname;
  return <div className="app"><AppSidebar pending={pending} /><main><div className="inner">{page === "/chat" ? <Chat data={data} /> : page === "/backlog" ? <Flow data={data} onCreate={onCreate} /> : page === "/reviews" ? <Reviews data={data} /> : page === "/projects" ? <Projects data={data} /> : page === "/providers" ? <Providers data={data} /> : page === "/analytics" ? <Analytics data={data} /> : page === "/settings" ? <Settings data={data} /> : <Overview data={data} onCreate={onCreate} />}</div></main></div>;
}
